#!/usr/bin/env bash

## Basic Setup
apt-get update
apt-get upgrade -y
apt-get install -y software-properties-common curl git build-essential
apt-get install -y sudo
apt-add-repository -y ppa:ansible/ansible
apt-get update
apt-get install -y curl git ansible build-essential
apt-get clean autoclean
apt-get autoremove --yes

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

## Pull Ansible
# sudo ansible-pull -U https://github.com/sarthikg/ansible.git