- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "/home/sarthikg/.ssh/id_rsa"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include: tasks/create_user.yml
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/git.yml
    - include: tasks/node.yml
    - include: tasks/npm.yml
