- hosts: localhost
  # 1. Variables for the ansible-playbook
  vars:
    home: "/home/{{user}}"
    current: "."

  vars_prompt:
    - name: user
      prompt: What username is the user being configured for?
      private: false
      default: "vagrant"

  # 2. Update Apt as a pre-task
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  # 3. Execute all the tasks
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/git.yml
    - include: tasks/node.yml
    - include: tasks/python.yml
