- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

- name: npmjs prefix
  shell: mkdir -p /home/sarthikg/.local/.npm-global
  become: true
  tags:
    - install
    - node

- name: add npmjs to path
  shell: PATH=/home/sarthikg/.local/.npm-global/bin:$PATH
  tags:
    - install
    - node

- name: npmjs global settings
  shell: npm config set prefix '/home/sarthikg/.local/.npm-global'
  tags:
    - install
    - node

- name: Install N
  become: true
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Install correct version of Node
  shell: n 18
  become: true
  tags:
    - install
    - node
    - test
