- name: Install NodeJS & NPM
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

- name: Add NPM Prefix
  shell: "mkdir -p {{home}}/.local/.npm-global"
  become: true
  tags:
    - install
    - node

- name: Add NPM to PATH
  shell: "PATH={{home}}/.local/.npm-global/bin:$PATH"
  tags:
    - install
    - node

- name: Configure NPM Global Settings
  shell: "npm config set prefix '{{home}}/.local/.npm-global'"
  tags:
    - install
    - node

- name: Install N
  become: true
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Install Node 18
  shell: exec $SHELL && n 18
  tags:
    - install
    - node
