- name: Install pip
  become: true
  apt:
    name: ["python3-pip"]
  tags:
    - install
    - python

# Add installation & configuration for pyenv

- name: Install thefuck
  become: false
  ansible.builtin.pip:
    name: thefuck
    executable: pip
  tags:
    - install
    - python
