- name: Ensure .ssh directory exists.
  become: true
  file:
    dest: "{{ home }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Install SSH private key
  become: true
  copy:
    src: "{{ current }}/.ssh/id_rsa"
    dest: "{{ home }}/.ssh/id_rsa"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install SSH public key
  become: true
  copy:
    src: "{{ current }}/.ssh/id_rsa.pub"
    dest: "{{ home }}/.ssh/id_rsa.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
