- name: Install ZSH
  become: true
  apt: name=zsh
  tags: &tags_for_zsh_tasks ["install", "productivity", "dotfiles", "zsh"]

- name: Set login shell of user sarthikg to `/usr/bin/zsh` with `usermod`
  ansible.builtin.command: usermod --shell /usr/bin/zsh sarthikg
  become: true
  changed_when: false
  tags: *tags_for_zsh_tasks

- name: Copy zshrc config file
  become: true
  copy:
    dest: "/home/sarthikg/.zshrc"
    src: "./dotfiles/.zshrc"
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  become: true
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > /home/sarthikg/.oh-my-installer && chmod +x /home/sarthikg/.oh-my-installer && /home/sarthikg/.oh-my-installer
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  become: true
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "/home/sarthikg/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks
# TO BE DONE
# 1. Install thefuck
# 2. Install bliss theme
